source: https://raw.githubusercontent.com/stencila/stencila/refs/heads/main/docs/reference/schema/config/config-models.md
description: Schema reference for  config config-models
title: Schema -  config config-models
config:
  publish:
    ghost:
      tags: ['#schema', '#doc', 'Config']
      state: publish
      type: post
