source: https://raw.githubusercontent.com/stencila/stencila/refs/heads/main/docs/reference/schema/other/product.md
description: Schema reference for  other product
title: Schema -  other product
config:
  publish:
    ghost:
      tags: ['#schema', '#doc', 'Other']
      state: publish
      type: post
